alter session set "_ORACLE_SCRIPT" = true;
-- Задание №1 --
SELECT name, open_mode FROM v$pdbs;
SELECT pdb_name, pdb_id, status FROM SYS.dba_pdbs;

-- Задание №2 --
SELECT * FROM v$instance;

-- Задание №3 --
SELECT * FROM SYS.PRODUCT_COMPONENT_VERSION;

-- Задание №4 --
CREATE PLUGGABLE DATABASE SAA_PDB
ADMIN USER pdb_admin IDENTIFIED BY 123456
ROLES = (DBA)
FILE_NAME_CONVERT =('/u02/app/oracle/oradata/ORCL/pdbseed', '/u02/app/oracle/oradata/ORCL/SAA_PDB');

-- Задание №5 --
SELECT name, open_mode FROM v$pdbs;
SELECT name FROM v$pdbs;

alter pluggable database SAA_PDB open ;
-- Задание №6 (Это уже на PDB)
CREATE TABLESPACE TS_SAA
DATAFILE 'TS_PDB.dbf'
SIZE 7M
AUTOEXTEND ON NEXT 5M
MAXSIZE 30M;

CREATE TEMPORARY TABLESPACE TS_SAA_TEMP
TEMPFILE 'TS_PDB_TEMP.dbf'
SIZE 5M
AUTOEXTEND ON NEXT 3M
MAXSIZE 30M;

CREATE ROLE RL_SAA;
GRANT  CREATE SESSION,
CREATE TABLE,
    CREATE VIEW,
    CREATE PROCEDURE,
    CREATE ANY PROCEDURE,
    DROP ANY TABLE,
    DROP ANY VIEW,
    DROP ANY PROCEDURE TO RL_SAA;
COMMIT;


DROP ROLE RL_SAA;

CREATE PROFILE PF_PDB_SAA LIMIT
PASSWORD_LIFE_TIME 180
SESSIONS_PER_USER 3
FAILED_LOGIN_ATTEMPTS 7
PASSWORD_LOCK_TIME 174
PASSWORD_REUSE_TIME 10
PASSWORD_GRACE_TIME DEFAULT
CONNECT_TIME 180
IDLE_TIME 30;

CREATE USER U1_SAA_PDB IDENTIFIED BY 123456
DEFAULT TABLESPACE TS_SAA
TEMPORARY TABLESPACE TS_SAA_TEMP
PROFILE default
ACCOUNT UNLOCK;

DROP USER U1_SAA_PDB;

GRANT RL_SAA TO U1_SAA_PDB;
GRANT dba to U1_SAA_PDB;
-- Задание №7 --
create  table  SAA_TABLE (
    Name nvarchar2(20),
    Age number
);

drop table SAA_TABLE;
ALTER SESSION SET CURRENT_SCHEMA = SAA_PDB;
SELECT * FROM USER_SYS_PRIVS;

GRANT CREATE SESSION TO U1_SAA_PDB;
grant DBA to U1_SAA_PDB;
COMMIT;


INSERT INTO SAA_TABLE (Name, Age) VALUES ('Andrey', 19);
INSERT INTO SAA_TABLE (Name, Age) VALUES ('Sanya', 19);
INSERT INTO SAA_TABLE (Name, Age) VALUES ('Oleg', 20);
INSERT INTO SAA_TABLE (Name, Age) VALUES ('Dimon', 20);

-- Задание №8 --

SELECT TABLESPACE_NAME, STATUS, CONTENTS FROM USER_TABLESPACES;
SELECT TABLESPACE_NAME, FILE_NAME FROM DBA_DATA_FILES;
SELECT TABLESPACE_NAME, FILE_NAME FROM DBA_TEMP_FILES;
SELECT * FROM DBA_ROLES;
SELECT * FROM DBA_ROLE_PRIVS ORDER BY GRANTEE;
SELECT * FROM DBA_PROFILES ORDER BY PROFILE;
SELECT * FROM DBA_USERS ORDER BY USERNAME;
SELECT USERNAME, GRANTED_ROLE FROM DBA_USERS JOIN DBA_ROLE_PRIVS ON USERNAME = GRANTEE ORDER BY USERNAME;

-- Задани 9 --

CREATE USER C##SAA IDENTIFIED BY 123456
ACCOUNT UNLOCK;

GRANT CREATE SESSION TO C##SAA;

DROP USER  C##SAA;
alter session set container= SAA_PDB;
alter session set container= CDB;
-- Задание №11
SELECT * FROM v$session WHERE username IS NOT NULL;

-- Задание №12
SELECT *  FROM DBA_DATA_FILES;

-- Задание №13
ALTER PLUGGABLE DATABASE SAA_PDB CLOSE IMMEDIATE;
DROP PLUGGABLE DATABASE  SAA_PDB including datafiles;
DROP USER C##SAA;