--1
CREATE TABLESPACE TS_SAA
DATAFILE 'TS_SAA.dat'
SIZE 7M
AUTOEXTEND ON
NEXT 5M
MAXSIZE 20M;
commit;
--2
CREATE TEMPORARY TABLESPACE TS_SAA_TEMP
TEMPFILE 'TS_SAA_TEMP.dat'
SIZE 5M
AUTOEXTEND ON
NEXT 3M
MAXSIZE 30M;
commit;
--3
select TABLESPACE_NAME from DBA_TABLESPACES;
--4
alter session set "_ORACLE_SCRIPT" = true;

CREATE ROLE C##RL_SAACORE;
GRANT
    CREATE SESSION,
    CREATE TABLE,
    CREATE VIEW,
    CREATE PROCEDURE,
    CREATE ANY PROCEDURE,
    DROP ANY TABLE,
    DROP ANY VIEW,
    DROP ANY PROCEDURE
    TO C##RL_SAACORE;
commit;


SELECT privilege
FROM dba_sys_privs
WHERE grantee = 'DB_USER';
--5
select * from DBA_ROLES;

--6
--docker exec -it oracle_db bash -c "source /home/oracle/.bashrc; sqlplus /nolog"

CREATE PROFILE C##PFf_SAACORE LIMIT
    PASSWORD_LIFE_TIME  180
    SESSIONS_PER_USER 3
    FAILED_LOGIN_ATTEMPTS 7
    PASSWORD_LOCK_TIME 1
    PASSWORD_REUSE_TIME 10
    PASSWORD_GRACE_TIME DEFAULT
    CONNECT_TIME 180
    IDLE_TIME 30;

COMMIT;
--7
select * from DBA_PROFILES;
select *
from DBA_PROFILES
where PROFILE = 'DEFAULT';
--8
CREATE USER SAACORE IDENTIFIED BY 12345
DEFAULT TABLESPACE TS_SAA QUOTA UNLIMITED ON TS_SAA
TEMPORARY TABLESPACE TS_SAA_TEMP
PROFILE C##PF_SAACORE
ACCOUNT UNLOCK
PASSWORD EXPIRE;

GRANT C##RL_SAACORE TO SAACORE;
COMMIT;

drop user SAACORE;
--9
--PASSWORD: 12345
--PASSWORD: 123456
--10

SELECT * FROM DBA_SYS_PRIVS WHERE GRANTEE = 'SAACORE';


create table testSAACORE(
    id int,
    str1 nvarchar2(12),
    str2 nvarchar2(50)
);



CREATE VIEW testSAACORE_View AS
SELECT id, str1, str2
FROM testSAACORE;

--11
CREATE TABLESPACE SAA_QDATA
    DATAFILE 'SAA_qdata.dat'
    SIZE 10M reuse
    offline;

ALTER TABLESPACE SAA_QDATA ONLINE;


ALTER USER SAACORE QUOTA 2M ON SAA_QDATA;

CREATE TABLE SAA_T1 (
    ID NUMBER,
    NAME VARCHAR2(50)
);

INSERT INTO SAA_T1 (ID, NAME) VALUES (1, 'str1');
INSERT INTO SAA_T1 (ID, NAME) VALUES (2, 'str2');
INSERT INTO SAA_T1 (ID, NAME) VALUES (3, 'str3');

select * from SAA_T1;

DROP TABLESPACE SAA_QDATA INCLUDING CONTENTS;